FROM node:20.12.0-alpine3.19

WORKDIR /user/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps

#install dependencies
RUN npm install

RUN cd package/db && npx prisma generate && cd ../..


RUN npm run build

CMD ["npm","run","start-user-app"]