FROM node:20.12.0-alpine3.19

ARG DATABASE_URL

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json ./

ENV DATABASE_URL=${DATABASE_URL}

COPY apps ./apps
COPY packages ./packages


ENV DATABASE_URL=${DATABASE_URL}

#install dependencies
RUN npm install

RUN cd packages/db && npx prisma generate && cd ../..

ENV DATABASE_URL=${DATABASE_URL}

RUN npm run build:user

CMD ["npm","run","start-user-app"]